export { default as DataAnalysisInst } from "./UsernameEnter/DataAnalysisInst/ui"
export { default as AccessToApp } from "./AccountCreating/AccessToApp/ui"
export { default as PayWindow } from "./GetPaidAccount/PayWindow/ui"
export { default as RegisterPayment } from "./GetPaidAccount/RegisterPayment/ui"
export { default as InstAnalysis } from "./EnterAccount/InstAnalysis/ui"
export { default as Authorization } from "./LogIn-Restore/Authorization/ui"
export { default as Restore } from "./LogIn-Restore/Restore/ui"
export { default as HeaderMenu } from "./AccountInformation/HeaderMenu/ui"
