export { default as StartNavigation } from "./OnBoarding/StartNavigation/ui"
export { default as DataAnalysisInst } from "./UsernameEnter/DataAnalysisInst/ui"
export { default as AccessToApp } from "./AccountCreating/AccessToApp/ui"
export { default as PayWindow } from "./GetPaidAccount/PayWindow/ui"
export { default as RegisterPayment } from "./GetPaidAccount/RegisterPayment/ui"